version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - server
    networks:
      - app-network
    volumes:
      - ./Wilspun-LMS-Service:/usr/code/client

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /home/ubuntu/apps/LMS/uploads:/usr/share/nginx/html/uploads
  #   depends_on:
  #     - client
  #   networks:
  #     - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
